export const JOB_CATE_LOAD_REQUEST="JOB_CATE_LOAD_REQUEST"
export const JOB_CATE_LOAD_SUCCESS="JOB_CATE_LOAD_SUCCESS"
export const JOB_CATE_LOAD_FAIL="JOB_CATE_LOAD_FAIL"
export const JOB_CATE_LOAD_RESET="JOB_CATE_LOAD_RESET"